[package]
name = "pkg-installer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
listenfd = "1.0.2"
nix = { version = "0.31.3", features = ["socket", "user"] }
pkg-core = { path = "../pkg-core" }
pkg-nix = { path = "../pkg-nix" }

[dev-dependencies]
pkg-testkit = { path = "../pkg-testkit" }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "deny"
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"

[[bin]]
name = "pkg-root-helper"
path = "src/bin/pkg-root-helper.rs"
