FROM rust:1.96-bookworm AS builder

ARG PKG_SYSTEM=x86_64-linux
WORKDIR /workspace
COPY . .

RUN test "$PKG_SYSTEM" = x86_64-linux
RUN --mount=type=cache,id=pkg-linux-registry,target=/usr/local/cargo/registry \
    --mount=type=cache,id=pkg-linux-target,target=/target \
    CARGO_TARGET_DIR=/target cargo run --locked --release \
        -p pkg-release --example linux_proof_publication -- \
        --prepare /proof-signing
RUN --mount=type=cache,id=pkg-linux-registry,target=/usr/local/cargo/registry \
    --mount=type=cache,id=pkg-linux-target,target=/target \
    PKG_RELEASE_TUF_ROOT_JSON="$(cat /proof-signing/root.json)" \
    PKG_RELEASE_CHANNEL_METADATA_URL=https://127.0.0.1:8443/metadata/ \
    PKG_RELEASE_CHANNEL_TARGETS_URL=https://127.0.0.1:8443/targets/ \
    CARGO_TARGET_DIR=/target cargo build --locked --release \
        -p pkg-cli --bin pkg \
        -p pkg-installer --bin pkg-nix-broker \
        -p pkg-installer --bin pkg-root-helper \
        -p pkg-installer --bin pkg-install \
    && mkdir /binaries \
    && cp /target/release/pkg /target/release/pkg-nix-broker \
        /target/release/pkg-root-helper /target/release/pkg-install /binaries/
RUN curl -fL --retry 3 \
    --output /tmp/nix.tar.xz \
    https://releases.nixos.org/nix/nix-2.34.8/nix-2.34.8-x86_64-linux.tar.xz \
    && printf '%s  %s\n' \
        2c2e146b80834fe0ca201b51deeb939405b4f18e8d2071bf80b10f8123c50464 \
        /tmp/nix.tar.xz \
        | sha256sum --check --strict
RUN --mount=type=cache,id=pkg-linux-registry,target=/usr/local/cargo/registry \
    --mount=type=cache,id=pkg-linux-target,target=/target \
    CARGO_TARGET_DIR=/target cargo run --locked --release \
        -p pkg-release --example linux_proof_publication -- \
        /publication-1 /tmp/nix.tar.xz /binaries "$PKG_SYSTEM" /proof-signing 1
RUN --mount=type=cache,id=pkg-linux-registry,target=/usr/local/cargo/registry \
    --mount=type=cache,id=pkg-linux-target,target=/target \
    CARGO_TARGET_DIR=/target cargo run --locked --release \
        -p pkg-release --example linux_proof_publication -- \
        /publication-2 /tmp/nix.tar.xz /binaries "$PKG_SYSTEM" /proof-signing 2
RUN mkdir /out \
    && cp -a /publication-1 /publication-2 /out/ \
    && mkdir /out/binaries \
    && cp /binaries/pkg-install /out/binaries/

FROM scratch
COPY --from=builder /out /
